application: aura--art
version: 1
runtime: php55
api_version: 1
threadsafe: no

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /(.+\.(gif|png|jpg|css|js|html|eot|woff|ttf|svg|otf|xml|txt|json|pdf))$
  static_files: \1
  upload: .+\.(gif|png|jpg|css|js|html|eot|woff|ttf|svg|otf|xml|txt|json|pdf)$
  application_readable: true

- url: /payment.php
  script: payment.php

- url: /.*
  script: index.php


skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^node_modules$
- ^appengine$
